# Generated by Django 2.1 on 2019-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_2', '0002_applyleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='Type_of_Request',
            field=models.CharField(choices=[('Sick_Leave', 'Sick Leave Request'), ('Vocational_Leave', 'Vacation Leave Request'), ('General_Leave', 'General Leave Request'), ('Night_Shift', 'Night Shift Request'), ('Work_From_Home', 'WorkFromHome Request')], max_length=25),
        ),
    ]
