# Generated by Django 2.1 on 2019-05-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_2', '0006_auto_20190514_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='leave_status',
            field=models.BooleanField(default=False),
        ),
    ]
