# Generated by Django 2.1 on 2019-06-13 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports_2', '0011_auto_20190609_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFromHomePolicyCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workfromhome',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports_2.WorkFromHomePolicyCase'),
            preserve_default=False,
        ),
    ]
