# Generated by Django 2.1 on 2018-08-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=25)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(null=True)),
                ('project_status', models.CharField(max_length=25)),
            ],
        ),
    ]
