# Generated by Django 2.1 on 2018-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_userslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSummaryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=25)),
                ('duration', models.CharField(max_length=25)),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userslist',
            name='user_id',
            field=models.CharField(max_length=25),
        ),
    ]
