# Generated by Django 2.1 on 2018-09-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180831_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('cretaed_at', models.DateField()),
                ('what_was_done_this_day', models.TextField()),
                ('what_is_your_plan_for_the_next_day', models.TextField()),
                ('what_are_your_blockers', models.TextField()),
                ('do_you_have_enough_tasks_for_next_three_days', models.TextField()),
                ('if_you_get_stuck_are_you_still_able_to_work_on_something_else', models.TextField()),
            ],
        ),
    ]
