# Generated by Django 2.1 on 2018-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_userdailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=70)),
                ('password', models.TextField()),
                ('joined_date', models.DateField()),
            ],
        ),
    ]
