# Generated by Django 2.1 on 2018-10-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remainingaccruedleaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainingaccruedleaves',
            name='till_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
