# Generated by Django 2.1 on 2019-01-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_userxmldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainingaccruedleaves',
            name='till_month',
        ),
    ]
