# Generated by Django 2.1 on 2019-06-11 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('from_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('logged_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('duration', models.CharField(max_length=4)),
                ('project_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('user_ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistIpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=20)),
            ],
        ),
    ]
