# Generated by Django 2.1 on 2019-05-28 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountNumber',
            new_name='BankAccountNumbers',
        ),
    ]
